---
- hosts: drbl
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt and install btrfs
      ansible.builtin.apt:
        pkg:
          - btrfs-tools
        state: latest
        update_cache: true
    - name: Create a btrfs filesystem on /dev/sdb
      community.general.filesystem:
        fstype: btrfs
        dev: /dev/sdb
    - name: Create btrfs Docker mount point 
      ansible.builtin.file:
        path: /var/lib/docker
        state: directory
        mode: '0710'
    - name: Mount up btrfs
      ansible.posix.mount:
        path: /var/lib/docker
        src: /dev/sdb
        fstype: btrfs
        opts: rw
        state: mounted
    - name: Copy Docker config
      ansible.builtin.copy:
        src: /vagrant/ansible/docker
        dest: /etc/
        owner: root
        group: root
    - name: Add Docker GPG apt key
      ansible.builtin.shell:
        cmd: |
          mkdir -m 0755 -p /etc/apt/keyrings && \
          (curl -fsSL https://download.docker.com/linux/debian/gpg |\
          gpg --dearmor -o /etc/apt/keyrings/docker.gpg)
        creates: /etc/apt/keyrings/docker.gpg
    - name: Add Docker Repository
      ansible.builtin.shell:
        cmd: |
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        creates: /etc/apt/sources.list.d/docker.list
    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
    - name: Clean APT repository
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
    - name: Add vagrant user to Docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true
    # platform is not working
    # - name: Build DRBL image
    #   community.docker.docker_image:
    #     name: andzuc/debian-drbl
    #     source: build
    #     force_source: true
    #     build:
    #       path: /vagrant/context
    #       platform: linux/386
    # using shell to build
    - name: Build DRBL image
      ansible.builtin.shell:
        cmd: ./build.sh
        chdir: /vagrant
