---
- hosts: drbl
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Add Docker GPG apt key
      shell:
        cmd: |
          mkdir -m 0755 -p /etc/apt/keyrings && \
          (curl -fsSL https://download.docker.com/linux/debian/gpg |\
          gpg --dearmor -o /etc/apt/keyrings/docker.gpg)
        creates: /etc/apt/keyrings/docker.gpg
    - name: Add Docker Repository
      shell:
        cmd: |
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        creates: /etc/apt/sources.list.d/docker.list
    - name: Update apt and install docker-ce
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
    - name: Clean APT repository
      apt:
        autoremove: true
        autoclean: true
    - name: Install Docker Module for Python
      pip:
        name: docker
        
    - name: Build DRBL image
      community.docker.docker_image:
        name: andzuc/debian-drbl
        source: build
        build:
          path: /vagrant/context
